// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thlggbiirbsaoxngxzxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRobGdnYmlpcmJzYW94bmd4enhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjQzMjQsImV4cCI6MjA3MTM0MDMyNH0.kKYsilLFoWYHBp9gmPOpB1P4JIBtE5OMfzHO7hAPyuE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});